-- ==============================================================================
-- 02_disposable_domains.sql
-- Conversational Digital Twin Resume Assistant
-- Disposable Email Blocklist Seed Data (Top known disposable/throwaway domains)
-- ==============================================================================

insert into public.disposable_email_domains (domain) values
('10minutemail.com'),
('10minutemail.net'),
('10minutemail.org'),
('10minmail.com'),
('20minutemail.com'),
('anonbox.net'),
('burnermail.io'),
('crazymailing.com'),
('dispostable.com'),
('dropmail.me'),
('emailondeck.com'),
('fakeinbox.com'),
('fakemailgenerator.com'),
('generator.email'),
('getairmail.com'),
('getnada.com'),
('guerrillamail.biz'),
('guerrillamail.com'),
('guerrillamail.de'),
('guerrillamail.net'),
('guerrillamail.org'),
('guerrillamailblock.com'),
('incognitomail.org'),
('inboxkitten.com'),
('maildrop.cc'),
('mailinator.com'),
('mailinator.net'),
('mailinator2.com'),
('mailnesia.com'),
('mailnull.com'),
('mohmal.com'),
('mytrashmail.com'),
('mytemp.email'),
('nada.ltd'),
('nada.ltd'),
('sharklasers.com'),
('spam4.me'),
('spambox.us'),
('spamfree24.org'),
('spamgourmet.com'),
('temp-mail.org'),
('tempmail.com'),
('tempmail.net'),
('tempmailaddress.com'),
('throwawaymail.com'),
('trashmail.com'),
('trashmail.net'),
('trashmail.org'),
('yopmail.com'),
('yopmail.fr'),
('yopmail.net'),
('zippymail.info'),
('disposablemail.com'),
('grr.la'),
('pokemail.net')
on conflict (domain) do nothing;
